#!/bin/bash
# Flutter Web 打包脚本
# 用法: ./build-web.sh

set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
FLUTTER_DIR="$PROJECT_DIR"

echo "=== Flutter Web 打包开始 ==="
echo "项目目录: $FLUTTER_DIR"
echo ""

# 自动递增版本号
increment_version() {
    local pubspec="$FLUTTER_DIR/pubspec.yaml"
    if [ ! -f "$pubspec" ]; then
        echo "  pubspec.yaml not found, skipping version increment"
        return
    fi

    # 读取当前版本号
    local current_version=$(grep "^version:" "$pubspec" | sed 's/version: *//' | tr -d ' ')
    echo "  当前版本: $current_version"

    # 解析版本号格式: major.minor.patch+build
    if [[ "$current_version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\+([0-9]+)$ ]]; then
        local major="${BASH_REMATCH[1]}"
        local minor="${BASH_REMATCH[2]}"
        local patch="${BASH_REMATCH[3]}"
        local build="${BASH_REMATCH[4]}"
        local new_build=$((build + 1))
        local new_version="${major}.${minor}.${patch}+${new_build}"
    elif [[ "$current_version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        local major="${BASH_REMATCH[1]}"
        local minor="${BASH_REMATCH[2]}"
        local patch="${BASH_REMATCH[3]}"
        local new_version="${major}.${minor}.${patch}+1"
    else
        echo "  无法解析版本号格式: $current_version"
        return
    fi

    echo "  新版本: $new_version"

    # 更新 pubspec.yaml
    sed -i.bak "s/^version:.*/version: $new_version/" "$pubspec"
    rm -f "$pubspec.bak"

    # 生成版本文件供 Flutter 代码使用
    local version_file="$FLUTTER_DIR/lib/version.g.dart"
    cat > "$version_file" << EOF
// GENERATED FILE - DO NOT MODIFY BY HAND
// This file is generated by the build script

const String appVersion = '$new_version';
EOF
    echo "  已生成版本文件: $version_file"
}

echo "递增版本号..."
increment_version
echo ""

# 获取依赖
echo "获取依赖..."
cd "$FLUTTER_DIR" && flutter pub get

# 构建 Web
echo "构建 Web..."
cd "$FLUTTER_DIR" && flutter build web

# 创建 zip 包
cd "$FLUTTER_DIR"
ZIP_NAME="flutter-web_$(date '+%Y-%m-%d-%H_%M_%S').zip"
echo "打包 Web 文件..."
zip -r "$ZIP_NAME" build/web/

echo ""
echo "=== Web 打包完成 ==="
echo "输出目录: $FLUTTER_DIR/build/web"
echo "ZIP 包: $FLUTTER_DIR/$ZIP_NAME"
