#!/bin/bash
# Flutter APK 打包脚本
# 用法: ./build-apk.sh

if [ -z "${BASH_VERSION:-}" ]; then
    exec bash "$0" "$@"
fi

set -e

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
FLUTTER_DIR="$PROJECT_DIR"
ANDROID_DIR="$FLUTTER_DIR/android"

echo "=== Flutter APK 打包开始 ==="
echo "项目目录: $FLUTTER_DIR"
echo ""

to_display_version() {
    local version="$1"
    if [[ "$version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\+([0-9]+)$ ]]; then
        echo "${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.$((${BASH_REMATCH[3]} + ${BASH_REMATCH[4]}))"
    else
        echo "$version"
    fi
}

read_pubspec_version() {
    local pubspec="$1"
    local line
    while IFS= read -r line; do
        case "$line" in
            version:*)
                line="${line#version:}"
                line="${line//[[:space:]]/}"
                echo "$line"
                return 0
                ;;
        esac
    done < "$pubspec"
    return 1
}

write_version_file() {
    local current_version="$1"
    local display_version
    display_version="$(to_display_version "$current_version")"
    local version_file="$FLUTTER_DIR/lib/version.g.dart"
    cat > "$version_file" << EOF
// GENERATED FILE - DO NOT MODIFY BY HAND
// This file is generated by the build script

const String appVersion = '$display_version';
EOF
    echo "  已更新版本文件: $version_file (版本: $display_version)"
}

# 自动递增版本号
increment_version() {
    local pubspec="$FLUTTER_DIR/pubspec.yaml"
    if [ ! -f "$pubspec" ]; then
        echo "  pubspec.yaml not found, skipping version increment"
        return
    fi

    # 读取当前版本号
    local current_version
    current_version="$(read_pubspec_version "$pubspec")"
    echo "  当前版本: $current_version"

    # 解析版本号格式: major.minor.patch+build
    # 如果没有 +build，则默认为 +1
    if [[ "$current_version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)\+([0-9]+)$ ]]; then
        local major="${BASH_REMATCH[1]}"
        local minor="${BASH_REMATCH[2]}"
        local patch="${BASH_REMATCH[3]}"
        local build="${BASH_REMATCH[4]}"
        local new_build=$((build + 1))
        # pubspec 格式带 +build
        local new_version="${major}.${minor}.${patch}+${new_build}"
        # APK 文件名格式: patch + build 合并，如 1.0.0+4 -> 1.0.4
        local display_version="${major}.${minor}.$((patch + build))"
    elif [[ "$current_version" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
        local major="${BASH_REMATCH[1]}"
        local minor="${BASH_REMATCH[2]}"
        local patch="${BASH_REMATCH[3]}"
        local new_version="${major}.${minor}.${patch}+1"
        local display_version="${major}.${minor}.${patch}"
    else
        echo "  无法解析版本号格式: $current_version"
        return
    fi

    echo "  新版本: $new_version"

    # 更新 pubspec.yaml
    sed -i.bak "s/^version:.*/version: $new_version/" "$pubspec"
    rm -f "$pubspec.bak"

    # 更新 android/app/build.gradle.kts 中的 versionCode
    local android_build_gradle="$ANDROID_DIR/app/build.gradle.kts"
    if [ -f "$android_build_gradle" ]; then
        # 提取当前 versionCode（如果没有则使用默认值 1）
        local current_version_code=$(grep -oP 'versionCode\s*=\s*\K\d+' "$android_build_gradle" 2>/dev/null || echo "1")
        local new_version_code=$((current_version_code + 1))
        sed -i.bak "s/versionCode\s*=\s*[0-9]\+/versionCode = $new_version_code/" "$android_build_gradle"
        rm -f "$android_build_gradle.bak"
        echo "  Android versionCode: $new_version_code"
    fi

}

echo "递增版本号..."
increment_version
echo ""

# 停止 Gradle 守护进程
echo "停止 Gradle 守护进程..."
cd "$ANDROID_DIR" && ./gradlew --stop 2>/dev/null || true

# 清理 Gradle 全局缓存（解决缓存损坏问题）
echo "清理 Gradle 缓存..."
rm -rf "$HOME/.gradle/caches/8.14/transforms" 2>/dev/null || true
rm -rf "$HOME/.gradle/caches/8.14/kotlin-script" 2>/dev/null || true
rm -rf "$HOME/.gradle/caches/8.14/fileHashes" 2>/dev/null || true
rm -rf "$HOME/.gradle/caches/8.14/jars-9" 2>/dev/null || true

# 清理项目 build 目录
echo "清理项目 build 目录..."
rm -rf "$FLUTTER_DIR/build" 2>/dev/null || true

# 配置国内镜像（阿里云）
configure_mirrors() {
    echo "配置国内镜像（阿里云）..."

    # 确保 gradle.properties 存在且包含必要配置
    GRADLE_PROPS="$ANDROID_DIR/gradle.properties"
    if [ -f "$GRADLE_PROPS" ]; then
        if ! grep -q "kotlin.incremental=false" "$GRADLE_PROPS"; then
            echo "kotlin.incremental=false" >> "$GRADLE_PROPS"
            echo "  已添加 kotlin.incremental=false"
        fi
    fi

    # 配置 settings.gradle.kts
    SETTINGS_FILE="$ANDROID_DIR/settings.gradle.kts"
    if [ -f "$SETTINGS_FILE" ]; then
        if ! grep -q "maven.aliyun.com" "$SETTINGS_FILE"; then
            cp "$SETTINGS_FILE" "$SETTINGS_FILE.bak"
            sed -i 's/repositories {/repositories {\n        maven { url = uri("https:\/\/maven.aliyun.com\/repository\/public") }\n        maven { url = uri("https:\/\/maven.aliyun.com\/repository\/google") }\n        maven { url = uri("https:\/\/maven.aliyun.com\/repository\/gradle-plugin") }/' "$SETTINGS_FILE"
            echo "  已更新 settings.gradle.kts"
        else
            echo "  settings.gradle.kts 已有阿里云镜像配置"
        fi
    fi

    # 配置 build.gradle.kts
    BUILD_FILE="$ANDROID_DIR/build.gradle.kts"
    if [ -f "$BUILD_FILE" ]; then
        if ! grep -q "maven.aliyun.com" "$BUILD_FILE"; then
            cp "$BUILD_FILE" "$BUILD_FILE.bak"
            sed -i 's/repositories {/repositories {\n        maven { url = uri("https:\/\/maven.aliyun.com\/repository\/public") }\n        maven { url = uri("https:\/\/maven.aliyun.com\/repository\/google") }/' "$BUILD_FILE"
            echo "  已更新 build.gradle.kts"
        else
            echo "  build.gradle.kts 已有阿里云镜像配置"
        fi
    fi

    echo "  国内镜像配置完成"
}

# 配置国内镜像
configure_mirrors

# 清理 Flutter 构建
echo "清理 Flutter 构建..."
cd "$FLUTTER_DIR" && flutter clean

# 获取依赖
echo "获取依赖..."
cd "$FLUTTER_DIR" && flutter pub get

# 在构建前生成版本文件，确保 APK 内嵌的是本次版本
echo "生成版本文件..."
CURRENT_VERSION="$(read_pubspec_version "$FLUTTER_DIR/pubspec.yaml")"
write_version_file "$CURRENT_VERSION"

# 构建 Release APK
echo "构建 Release APK..."
cd "$FLUTTER_DIR" && flutter build apk --release

# 重命名 APK 文件包含版本号
OUTPUT_DIR="$FLUTTER_DIR/build/app/outputs/flutter-apk"
STANDARD_APK="$OUTPUT_DIR/app-release.apk"
if [ -f "$STANDARD_APK" ]; then
    # 从 pubspec.yaml 读取版本号并转换为显示格式
    CURRENT_VERSION="$(read_pubspec_version "$FLUTTER_DIR/pubspec.yaml")"
    DISPLAY_VERSION="$(to_display_version "$CURRENT_VERSION")"
    VERSIONED_APK="$OUTPUT_DIR/app-release-${DISPLAY_VERSION}.apk"

    # 复制为版本化文件名
    cp "$STANDARD_APK" "$VERSIONED_APK"

    echo ""
    echo "=== APK 打包完成 ==="
    echo "标准路径: $STANDARD_APK"
    echo "版本化路径: $VERSIONED_APK"
else
    echo ""
    echo "=== APK 打包完成 ==="
    echo "输出路径: $STANDARD_APK"
fi
