# deploy-agent project deploy config
pack_pattern=deploy-agent_{date}.zip

# === Build config per platform ===
[build.win]
project_dir=E:\githubdesktop\go_blog\cmd\deploy-agent
pack_script=zip-files.bat

[build.linux]
project_dir=/data/program/deploy-agent
pack_script=zip-files.sh

# === Deploy targets ===
[target.local.win]
remote_dir=E:\githubdesktop\go_blog\cmd\deploy-agent
remote_script=publish.bat

[target.local.linux]
remote_dir=/data/program/deploy-agent
remote_script=publish.sh

