(() => {
    const palettes = ['#3f9c91','#dc704b','#325d80','#b68c43','#765e94'];
    const escapeHTML = (value) => { const span = document.createElement('span'); span.textContent = value || ''; return span.innerHTML; };
    const progress = (book) => book.total_pages > 0 ? Math.min(100,Math.round((book.current_page || 0) / book.total_pages * 100)) : 0;
    function cover(book,index,className) { return book.cover_url ? `<img src="${escapeHTML(book.cover_url)}" alt="">` : `<span style="--book:${palettes[index % palettes.length]}" class="${className}">${escapeHTML((book.title || '书').slice(0,1))}</span>`; }
    function readingRow(book,index) { const p = progress(book); return `<a class="reading-row" href="/reading/book/${encodeURIComponent(book.id)}">${book.cover_url ? `<img src="${escapeHTML(book.cover_url)}" alt="">` : `<i class="mini-book" style="--book:${palettes[index % palettes.length]}">${escapeHTML((book.title || '书').slice(0,1))}</i>`}<div class="reading-copy"><strong>${escapeHTML(book.title)}</strong><span>${book.current_page || 0} / ${book.total_pages || 0} 页</span></div><div class="row-progress"><i><b style="width:${p}%"></b></i><small>${p}%</small></div></a>`; }
    function finished(book,index) { return `<a class="finished-book" href="/reading/book/${encodeURIComponent(book.id)}"><div class="finished-cover" style="--book:${palettes[index % palettes.length]}">${book.cover_url ? `<img src="${escapeHTML(book.cover_url)}" alt="">` : escapeHTML((book.title || '书').slice(0,1))}</div><strong>${escapeHTML(book.title)}</strong></a>`; }
    async function load() { try { const [booksResponse,statsResponse] = await Promise.all([fetch('/api/books?sort_by=add_time&sort_order=desc'),fetch('/api/reading-statistics')]); if (!booksResponse.ok) throw new Error('读取失败'); const books = (await booksResponse.json()).books || []; const stats = statsResponse.ok ? await statsResponse.json() : {}; const reading = books.filter((book) => book.status === 'reading'); const finishedBooks = books.filter((book) => book.status === 'finished'); const total = stats.total_books || books.length; const done = stats.finished_books || finishedBooks.length; document.getElementById('totalBooks').textContent = total; document.getElementById('readingBooks').textContent = stats.reading_books || reading.length; document.getElementById('finishedBooks').textContent = done; document.getElementById('totalPages').textContent = stats.total_pages || books.reduce((sum,book) => sum + (book.total_pages || 0),0); document.getElementById('completionRate').textContent = total ? `${Math.round(done / total * 100)}%` : '0%'; document.getElementById('readingList').innerHTML = reading.length ? reading.slice(0,6).map(readingRow).join('') : '<p class="empty">还没有正在阅读的书。</p>'; document.getElementById('finishedList').innerHTML = finishedBooks.length ? finishedBooks.slice(0,8).map(finished).join('') : '<p class="empty">完成一本书，它会出现在这里。</p>'; const states = [{label:'阅读中',count:reading.length,color:'#3f9c91'},{label:'已读完',count:finishedBooks.length,color:'#dc704b'},{label:'未开始',count:books.filter((book) => book.status === 'unstart').length,color:'#325d80'},{label:'暂停',count:books.filter((book) => book.status === 'paused').length,color:'#b68c43'}]; const max = Math.max(1,...states.map((item) => item.count)); document.getElementById('statusChart').innerHTML = states.map((item) => `<div class="status-bar"><i style="--bar:${item.color};height:${Math.max(item.count ? 12 : 4,item.count / max * 100)}%"></i><span>${item.label}<br>${item.count}</span></div>`).join(''); document.getElementById('chartNote').textContent = reading.length ? `当前有 ${reading.length} 本书正在阅读，保持稳定推进。` : '挑选一本书，从十页开始建立阅读节奏。'; } catch { document.getElementById('readingList').innerHTML = '<p class="empty">阅读数据暂时无法加载。</p>'; } }
    load();
})();
